<?php

return [
    [
        'slug'        => 'malware-cleanup',
        'name'        => 'Emergency Malware Cleanup',
        'description' => 'Full scan, complete removal, post-hack hardening & report.',
        'price'       => 149,
        'price_label' => '$149',
        'billing'     => 'one-time',
        'requires_site' => true,
        'notes_label' => 'Describe the issue or any access details we should know.',
    ],
    [
        'slug'        => 'content-edits',
        'name'        => 'Extra Content Edit Hours',
        'description' => 'Text, images, minor layout changes — billed in 30-minute blocks.',
        'price'       => 65,
        'price_label' => '$65/hr',
        'billing'     => 'hourly',
        'requires_site' => true,
        'show_quantity' => true,
        'quantity_label' => 'Hours (30-min blocks)',
        'notes_label' => 'What would you like changed?',
    ],
    [
        'slug'        => 'speed-audit',
        'name'        => 'Speed Optimization Audit',
        'description' => 'Core Web Vitals deep-dive with a prioritised action plan.',
        'price'       => 99,
        'price_label' => '$99',
        'billing'     => 'one-time',
        'requires_site' => true,
        'notes_label' => 'Any specific pages or performance concerns?',
    ],
    [
        'slug'        => 'ssl-install',
        'name'        => 'SSL Installation & Verification',
        'description' => 'We install, configure, force HTTPS, and verify end-to-end.',
        'price'       => 49,
        'price_label' => '$49',
        'billing'     => 'one-time',
        'requires_site' => true,
        'notes_label' => 'Hosting access notes (if not already on file).',
    ],
    [
        'slug'        => 'backup-storage',
        'name'        => 'Extra Backup Storage',
        'description' => 'Per 10 GB of additional secure cloud storage.',
        'price'       => 9,
        'price_label' => '$9/mo',
        'billing'     => 'monthly',
        'requires_site' => true,
        'show_quantity' => true,
        'quantity_label' => 'Extra 10 GB blocks',
        'notes_label' => 'Optional notes for our team.',
    ],
    [
        'slug'        => 'emergency-restore',
        'name'        => 'One-Time Emergency Restore',
        'description' => 'On-demand restore for Monitor plan clients (no SLA).',
        'price'       => 99,
        'price_label' => '$99',
        'billing'     => 'one-time',
        'requires_site' => true,
        'notes_label' => 'What happened and what date should we restore to?',
    ],
];
