<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Invoice — client billing invoice, generated on Whop charge.succeeded.
 *
 * Amounts stored in cents (integers) to avoid float precision issues.
 * PDFs generated by Puppeteer, stored on Backblaze B2.
 *
 * @property string  $id
 * @property string  $tenant_id
 * @property string  $client_id
 * @property string|null $subscription_id
 * @property string  $invoice_number     RVG-YYYY-NNN
 * @property \Carbon\Carbon $period_start
 * @property \Carbon\Carbon $period_end
 * @property \Carbon\Carbon $issued_at
 * @property int     $subtotal_cents
 * @property int     $tax_cents
 * @property int     $total_cents
 * @property string  $currency
 * @property array   $line_items
 * @property string  $status             'paid'|'unpaid'|'void'
 * @property string|null $whop_charge_id
 * @property string|null $pdf_b2_key
 * @property string|null $pdf_url
 * @property \Carbon\Carbon|null $pdf_generated_at
 */
class Invoice extends Model
{
    use HasUuids;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $fillable = [
        'tenant_id',
        'client_id',
        'subscription_id',
        'invoice_number',
        'period_start',
        'period_end',
        'issued_at',
        'subtotal_cents',
        'tax_cents',
        'total_cents',
        'currency',
        'line_items',
        'status',
        'whop_charge_id',
        'pdf_b2_key',
        'pdf_url',
        'pdf_generated_at',
    ];

    protected $casts = [
        'period_start'     => 'date',
        'period_end'       => 'date',
        'issued_at'        => 'date',
        'subtotal_cents'   => 'integer',
        'tax_cents'        => 'integer',
        'total_cents'      => 'integer',
        'line_items'       => 'array',
        'pdf_generated_at' => 'datetime',
    ];

    // ── Amount helpers ────────────────────────────────────────────────────────

    /** Total in dollars (for display) */
    public function getTotalAttribute(): float
    {
        return $this->total_cents / 100;
    }

    public function getSubtotalAttribute(): float
    {
        return $this->subtotal_cents / 100;
    }

    public function getTaxAttribute(): float
    {
        return $this->tax_cents / 100;
    }

    public function getFormattedTotalAttribute(): string
    {
        return '$' . number_format($this->total_cents / 100, 2);
    }

    // ── Relationships ─────────────────────────────────────────────────────────

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function subscription(): BelongsTo
    {
        return $this->belongsTo(Subscription::class);
    }
}
