<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Invoice — client billing invoice, generated on Stripe invoice.paid webhook.
 *
 * Amounts stored in cents (integers) to avoid float precision issues.
 * PDFs generated by Puppeteer, stored on Backblaze B2.
 *
 * @property string  $id
 * @property string  $tenant_id
 * @property string  $client_id
 * @property string|null $subscription_id
 * @property string  $invoice_number     RVG-YYYY-NNN
 * @property \Carbon\Carbon $period_start
 * @property \Carbon\Carbon $period_end
 * @property \Carbon\Carbon $issued_at
 * @property int     $subtotal_cents
 * @property int     $tax_cents
 * @property int     $total_cents
 * @property string  $currency
 * @property array   $line_items
 * @property string  $status             'paid'|'unpaid'|'void'
 * @property string|null $whop_charge_id
 * @property string|null $stripe_invoice_id
 * @property string|null $pdf_b2_key
 * @property string|null $pdf_url
 * @property \Carbon\Carbon|null $pdf_generated_at
 */
class Invoice extends Model
{
    use HasUuids;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $fillable = [
        'tenant_id',
        'client_id',
        'subscription_id',
        'invoice_number',
        'period_start',
        'period_end',
        'issued_at',
        'subtotal_cents',
        'tax_cents',
        'total_cents',
        'currency',
        'line_items',
        'status',
        'whop_charge_id',
        'stripe_invoice_id',
        'stripe_hosted_invoice_url',
        'reference_key',
        'pdf_b2_key',
        'pdf_url',
        'pdf_generated_at',
    ];

    protected $casts = [
        'period_start'     => 'date',
        'period_end'       => 'date',
        'issued_at'        => 'date',
        'subtotal_cents'   => 'integer',
        'tax_cents'        => 'integer',
        'total_cents'      => 'integer',
        'line_items'       => 'array',
        'pdf_generated_at' => 'datetime',
    ];

    // ── Amount helpers ────────────────────────────────────────────────────────

    /** Total in dollars (for display) */
    public function getTotalAttribute(): float
    {
        return $this->total_cents / 100;
    }

    public function getSubtotalAttribute(): float
    {
        return $this->subtotal_cents / 100;
    }

    public function getTaxAttribute(): float
    {
        return $this->tax_cents / 100;
    }

    public function getFormattedTotalAttribute(): string
    {
        return '$' . number_format($this->total_cents / 100, 2);
    }

    /** Short label for invoice list (from Stripe line items). */
    public function summaryDescription(): string
    {
        $items = $this->line_items ?? [];

        if ($items === []) {
            return 'ReviveGuard subscription';
        }

        $descriptions = array_values(array_filter(array_map(
            fn (array $item) => $item['description'] ?? null,
            $items,
        )));

        if ($descriptions === []) {
            return 'ReviveGuard subscription';
        }

        if (count($descriptions) === 1) {
            return $descriptions[0];
        }

        return $descriptions[0] . ' · ' . $descriptions[1];
    }

    public function isPlanChangeCredit(): bool
    {
        return $this->total_cents === 0
            && $this->reference_key !== null
            && str_starts_with($this->reference_key, 'plan_change:');
    }

    public function receiptUrl(): ?string
    {
        return $this->pdf_url ?: $this->stripe_hosted_invoice_url;
    }

    public function stripeDashboardUrl(): ?string
    {
        if (! $this->stripe_invoice_id) {
            return null;
        }

        return \App\Support\StripeDashboard::invoiceUrl($this->stripe_invoice_id);
    }

    public function statusLabel(): string
    {
        if ($this->isPlanChangeCredit()) {
            return 'Credit';
        }

        return ucfirst($this->status);
    }

    // ── Relationships ─────────────────────────────────────────────────────────

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function client(): BelongsTo
    {
        return $this->belongsTo(Client::class);
    }

    public function subscription(): BelongsTo
    {
        return $this->belongsTo(Subscription::class);
    }
}
