<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('clients', function (Blueprint $table) {
            // Hashed one-time token for magic-link account activation.
            // Generated by OnboardClientJob, cleared after first use.
            $table->string('activation_token', 255)->nullable()->after('portal_password');
            $table->timestampTz('activation_expires_at')->nullable()->after('activation_token');
        });
    }

    public function down(): void
    {
        Schema::table('clients', function (Blueprint $table) {
            $table->dropColumn(['activation_token', 'activation_expires_at']);
        });
    }
};
