<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

/**
 * invoices — client billing invoices, generated on Whop charge.succeeded webhook.
 *
 * PDFs generated by Puppeteer microservice, stored on Backblaze B2.
 * Clients download from portal Account → Billing tab.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('invoices', function (Blueprint $table) {
            $table->uuid('id')->primary()->default(DB::raw('gen_random_uuid()'));
            $table->foreignUuid('tenant_id')->constrained('tenants')->cascadeOnDelete();
            $table->foreignUuid('client_id')->constrained('clients')->cascadeOnDelete();
            $table->foreignUuid('subscription_id')->nullable()->constrained('subscriptions')->nullOnDelete();

            // Invoice number: RVG-YYYY-NNN (generated by InvoiceService)
            $table->string('invoice_number', 30)->unique();

            // Billing period
            $table->date('period_start');
            $table->date('period_end');
            $table->date('issued_at');

            // Amounts (in USD, stored as cents to avoid float issues)
            $table->unsignedInteger('subtotal_cents')->default(0);
            $table->unsignedInteger('tax_cents')->default(0);
            $table->unsignedInteger('total_cents')->default(0);
            $table->string('currency', 3)->default('USD');

            // Line items stored as JSON: [{description, quantity, unit_price_cents, total_cents}]
            $table->jsonb('line_items')->default('[]');

            // Payment status
            $table->string('status', 30)->default('paid');
            // 'paid' | 'unpaid' | 'void'

            // Whop charge reference
            $table->string('whop_charge_id', 100)->nullable()->unique();

            // PDF
            $table->string('pdf_b2_key', 500)->nullable();     // B2 object key
            $table->string('pdf_url', 1000)->nullable();        // signed URL (short-lived, refreshed on request)
            $table->timestampTz('pdf_generated_at')->nullable();

            $table->timestampsTz();
        });

        DB::statement('CREATE INDEX idx_invoices_tenant  ON invoices(tenant_id)');
        DB::statement('CREATE INDEX idx_invoices_client  ON invoices(client_id)');
        DB::statement('CREATE INDEX idx_invoices_number  ON invoices(invoice_number)');
        DB::statement('CREATE INDEX idx_invoices_charge  ON invoices(whop_charge_id)');
    }

    public function down(): void
    {
        Schema::dropIfExists('invoices');
    }
};
